### ISSUE TITLE
BUG: Something is hidind behind the chat button .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Nactore-Org/Nacto-Care#181] opened 2024-05-28 09:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Behind the chat button something is hiding .

![Screenshot 2024-05-28 152208](https://github.com/Nactore-Org/Nacto-Care/assets/118350936/e2600f73-303d-426f-9f7f-5cde4316dd1d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment] 2024-05-28 19:43
duplicate of #170

**Closed by Harshil-Jani** 2024-05-28 19:43 UTC
