### ISSUE TITLE
BUG:Menu is not opening on click

### ISSUE THREAD

**Issue by Venkatknight2295** [Nactore-Org/Nacto-Care#78] opened 2024-05-20 04:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

menu not working as expected 
![image](https://github.com/Nactore-Org/Nacto-Care/assets/118790430/71d1ba81-01e3-4ebc-b1b5-aade4b4cc790)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment] 2024-05-20 06:42
Duplicate of #73

**Closed by Harshil-Jani** 2024-05-20 06:42 UTC
