### ISSUE TITLE
BUG:In dark mode mobile ,elements are not visible

### ISSUE THREAD

**Issue by Rohitha-pudu** [Nactore-Org/Nacto-Care#123] opened 2024-05-23 15:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

In The dark mode of mobile ,the nav bar elements are not clearly visible
![image](https://github.com/Nactore-Org/Nacto-Care/assets/116823590/01ab1cbc-5886-4334-aa69-2f1adf8c7c0d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment] 2024-05-23 19:02
Duplicate of #99

**Closed by Harshil-Jani** 2024-05-23 19:02 UTC
