### ISSUE TITLE
Feat: Redirecting to Top issue

### ISSUE THREAD

**Issue by Hemashree21** [Nactore-Org/Nacto-Care#215] opened 2024-06-01 09:47 UTC
### Describe the feature

Whenever I scroll to the bottom of any one of the pages and then select another page, the page opened displays the bottom of the page instead of the starting section.

@Harshil-Jani can you please assign this to me?

### Add ScreenShots

![image](https://github.com/Nactore-Org/Nacto-Care/assets/138188163/555ac045-dc1a-4d24-816c-c314f8b60baa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment] 2024-06-02 19:17
Duplicate of #184

**Closed by Harshil-Jani** 2024-06-02 19:17 UTC
