### ISSUE TITLE
Feat: Burger Menu not working on responsive

### ISSUE THREAD

**Issue by dhruv8433** [Nactore-Org/Nacto-Care#61] opened 2024-05-17 14:43 UTC
### Describe the feature

@Nactore-Org

please checkout this the burger menu is not working on responsive devices

### Add ScreenShots

![image](https://github.com/Nactore-Org/Nacto-Care/assets/114583978/34621a65-31ad-4696-911d-d3fd8d864f8b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment] 2024-05-18 07:39
Duplicate of #34

**Closed by Harshil-Jani** 2024-05-18 07:39 UTC
