### ISSUE TITLE
BUG: The page requires smooth scrolling

### ISSUE THREAD

**Issue by aryansharma220** [Nactore-Org/Nacto-Care#202] opened 2024-05-30 15:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

https://github.com/Nactore-Org/Nacto-Care/assets/133234867/e825c5e8-8e8c-42dd-accc-50bc5b2d0f1c

The scrolling is not smooth.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment] 2024-06-02 19:01
Duplicate of #201

**Closed by Harshil-Jani** 2024-06-02 19:01 UTC
