### ISSUE TITLE
BUG: UI enhancement in Career Page

### ISSUE THREAD

**Issue by TenzDelek** [Nactore-Org/Nacto-Care#158] opened 2024-05-26 04:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

shifting the button for above md screen making it less larger than indented size.
current UI:
<img width="1206" alt="image" src="https://github.com/Nactore-Org/Nacto-Care/assets/122612557/4ddc6514-5f7c-471d-ba75-c91e8c4662f8">
Proposed UI:![212121](https://github.com/Nactore-Org/Nacto-Care/assets/122612557/85ef65f5-2106-43e1-b5d1-f1104a5f603f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment] 2024-05-26 06:45
There is whole redesign being done in career page. Duplicate of #104

**Closed by Harshil-Jani** 2024-05-26 06:45 UTC
