### ISSUE TITLE
Improve Footer: Adding functionality in footer 

### ISSUE THREAD

**Issue by Karankumar2004** [Nactore-Org/Nacto-Care#40] opened 2024-05-14 13:31 UTC
- Functional Links: Ensure all links in the footer, including navigation links to different pages, are functional and lead to the respective destinations.
- Hover Effects: Implement hover effects on footer elements to enhance interactivity and visual feedback for users.
- Social Media Integration: Add social media icons or links to relevant profiles/accounts within the footer.

@Harshil-Jani  let's collaborate to transform the footer into a professional and functional component that enhances the overall user experience of the open-source project!
Don't forgot to assign it under GSSoc 24.

**Comment by Harshil-Jani** [comment] 2024-05-16 18:03
Duplicate of #31

**Closed by Harshil-Jani** 2024-05-16 18:03 UTC
