### ISSUE TITLE
Feat: Signin with google 

### ISSUE THREAD

**Issue by mukilan2815** [Nactore-Org/Nacto-Care#229] opened 2024-06-03 14:47 UTC
### Describe the feature

We can add google signin option for users so that they will signin with one click 

### Add ScreenShots

![image](https://github.com/Nactore-Org/Nacto-Care/assets/71129858/1c8b410c-9fbf-42af-bc71-d3cb515db1c6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment] 2024-06-03 20:19
duplicate of #195

**Closed by Harshil-Jani** 2024-06-03 20:19 UTC
