### ISSUE TITLE
[Logo Design] Nacto-Care 

### ISSUE THREAD

**Issue by me-shweta** [Nactore-Org/Nacto-Care#82] opened 2024-05-20 10:06 UTC
### Describe the feature

 @Harshil-Jani I have made one logo. Let me know if this is fine or if you need more changes to the themes. I can create more designs like this with different orientations and adjustments. Let me know if you are interested in these designs.

### Add ScreenShots

<img width="174" alt="nactocare" src="https://github.com/Nactore-Org/Nacto-Care/assets/119609866/45729813-08a6-4a61-8cc8-a21c42a2261a">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment] 2024-05-20 10:10
Duplicate of #64

**Closed by Harshil-Jani** 2024-05-20 10:10 UTC
