### ISSUE TITLE
Feat: Make "Privacy policy" and "Terms and condition"  pages for Nacto Care 

### ISSUE THREAD

**Issue by Devaki01** [Nactore-Org/Nacto-Care#74] opened 2024-05-19 12:33 UTC
### Description
I would like to contribute by adding a Privacy policy and Terms and conditions page for Nacto Care. 

### Why add a Privacy Policy and Terms and conditions page
Users are more likely to trust and engage with a website that openly communicates its data practices. A privacy policy builds trust and transparency between users and the website as it openly communicates its data practices and the terms and conditions page helps protect the website owner from potential legal issues by clearly outlining the rules and guidelines users must follow when using the site.  

### Features
Relevant Content
Responsiveness and Interactivity
Visual appeal

### About Me
I am an aspiring developer and tech-enthusiast, especially passionate about Technologies such as React . As a GGSoC'24 contributor, I am looking forward to make the proposed contribution and promise to put all my efforts into it, hoping to learn a lot in the process.

Please assign me the issue under GGSoC'24

### Add ScreenShots

<img width="526" alt="image" src="https://github.com/Nactore-Org/Nacto-Care/assets/147143243/023a7f57-cb19-4b8f-995d-c78fe1b105c1">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment] 2024-05-20 06:19
Duplicate of #56

**Closed by Harshil-Jani** 2024-05-20 06:19 UTC
