### ISSUE TITLE
Fix : Improve the alignment of menu items in navbar in mobile screen 

### ISSUE THREAD

**Issue by Stiffpixels** [Nactore-Org/Nacto-Care#148] opened 2024-05-24 17:18 UTC
### Describe the feature

The navigation menu list items are hard to see on mobile.
The menu button is not positioned correctly i.e. to the right edge of the screen on mobile.

### Add ScreenShots

links not visible on mobile: 
![image](https://github.com/Nactore-Org/Nacto-Care/assets/32983571/86ff9eaf-6ba5-47d0-99bd-95f61529a472)
menu button not aligned properly:
![image](https://github.com/Nactore-Org/Nacto-Care/assets/32983571/d6f08857-eabb-4361-be2a-087440c5b4ac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment] 2024-05-24 18:20
Duplicate of #99

**Closed** 2024-05-25 05:32 UTC
Labels: gssoc, level2
