### ISSUE TITLE
Hamburger Menu is not working in Small screens.

### ISSUE THREAD

**Issue by avayyyyyyy** [Nactore-Org/Nacto-Care#39] opened 2024-05-13 08:13 UTC
<img width="1392" alt="Screenshot 2024-05-13 at 1 41 46 PM" src="https://github.com/Nactore-Org/Nacto-Care/assets/111121419/3ec12596-68df-40ff-abca-8f4019ac8f7e">

While clicking on the hamburger menu, it is not working...I can work on this issue can make this feature work.

Please assign this issue to me.

**Comment by Harshil-Jani** [comment] 2024-05-16 18:11
Duplicate of #34 . If you are still interested then please comment in #34 if not assigned to anyone else.

**Closed by Harshil-Jani** 2024-05-16 18:11 UTC
