### ISSUE TITLE
BUG: hamburger icon is not visible properly

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Nactore-Org/Nacto-Care#206] opened 2024-05-30 17:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/Nactore-Org/Nacto-Care/assets/125277258/dc82876a-0c68-4b08-8a02-494bd468bf76)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment] 2024-06-02 19:04
Duplicate of #204

**Closed by Harshil-Jani** 2024-06-02 19:04 UTC
