### ISSUE TITLE
Feat: Adding Google and github login and signup

### ISSUE THREAD

**Issue by harshmishra19** [Nactore-Org/Nacto-Care#221] opened 2024-06-02 19:50 UTC
### Describe the feature

This feature enables users to log in or sign up to the website using their Google or GitHub accounts. By integrating these popular authentication methods, users can quickly and securely access their accounts without the need to create and remember additional login credentials.

### Add ScreenShots

![login](https://github.com/Nactore-Org/Nacto-Care/assets/115486960/7d714ea0-8fc7-418d-8709-be8dd37f0a87)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment] 2024-06-03 04:22
duplicate of #195

**Closed by Harshil-Jani** 2024-06-03 04:22 UTC
