### ISSUE TITLE
DOC: Draft relevant content in the "our mission" and "our story" section

### ISSUE THREAD

**Issue by Devaki01** [Nactore-Org/Nacto-Care#75] opened 2024-05-19 12:37 UTC
### What's wrong with the existing documentation

The text in the site consists of Lorem Ipsum text.

### Add ScreenShots

<img width="337" alt="image" src="https://github.com/Nactore-Org/Nacto-Care/assets/147143243/1d6d318c-f71e-421a-9c0b-5a55bc6cb051">
<img width="419" alt="image" src="https://github.com/Nactore-Org/Nacto-Care/assets/147143243/ddb0858b-00a2-427c-87f2-2b3b3da3ab7c">

PLease assign me the issue under ggsoc'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment] 2024-05-20 09:06
Duplicate of #66 

@Devaki01 Can you find some issue to work with ? I am happy to assign that.

**Closed by Harshil-Jani** 2024-05-20 09:07 UTC
